version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

workflows:
  version: 2

  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint
